services:
  homeassistant:
    build: ./homeassistant
    container_name: homeassistant
    volumes:
      - ./custom_components:/config/custom_components
      - ./python_scripts:/config/python_scripts
    ports:
      - 8123:8123/tcp
      - 6454:6454/udp
    restart: unless-stopped
   
   