hello_hass:
  name: toggle switch
  description: Check Switch State and toggles
  fields:
    nome:
      description: um nome para escrever  no log
      example: "JotaPompo"
    entidade:
      description: O switch para fazer toggle
      example: "JotaPompo"